name: supermind
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.6
  - pandas=1.3.5
  - cython=0.29.32
  - pip
  - pip:
    - mgquant>=3.0.9
    - pyarrow==8.0.0
    - requests~=2.28.1
    - msgpack~=1.0.4
    - pyyaml~=5.4.1
    - cachetools~=5.2.0
    - xarray~=2022.10.0
    - tqdm~=4.64.1
    - protobuf~=3.11.4
    - zipline-reloaded==3.0.4